apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-template
spec:
  template:
    spec:
      containers:
        - name: go-api-template
          env:
            - name: LOG_OUTPUT
              value: "Stdout"
            - name: LOG_LEVEL
              value: "debug"
            - name: LOG_TIMESTAMP_FORMAT
              value: ""
            - name: LOG_ACCESS_LEVEL
              value: "trace"