apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
patchesStrategicMerge:
  - envHttp.yaml
  - envJaeger.yaml
  - envLog.yaml
  - envMongo.yaml
  - jaegerSidecar.yaml
commonLabels:
  app: go-api-template
